### ISSUE TITLE
`setup.cfg` isn't packaging Python library files

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/cookiecutter-brightwaylib#15]
One can see this by extracting the tarball after `python -m build` or by running `pip install . -vvv | grep adding`. Only the `dist-info` stuff is added.

There is something in the `setup.cfg` file, but after playing with the `packages = find:` or other options I can't make much progress, and [the setuptools user guide](https://setuptools.pypa.io/en/latest/userguide/declarative_config.html) isn't much help.

@tngTUDOR Any ideas?

**Comment by tngTUDOR** [comment]
I think this is related to:

https://github.com/brightway-lca/cookiecutter-brightwaylib/blob/main/%7B%7Bcookiecutter.project_name%7D%7D/setup.cfg#L48

**Comment by tngTUDOR** [comment]
this should have been fixed with:

https://github.com/brightway-lca/cookiecutter-brightwaylib/commit/85b6d642cd92c49fe3539e139010779e48016abd

**Comment by tngTUDOR** [comment]
does your setup.cfg specify "root" project folder as the place to find packages?
``` 44   │ [options]
  45   │ zip_safe = False
  46   │ packages = find_namespace:
  47   │ include_package_data = True
  48   │ package_dir =
  49 ~ │     = .
```
and:

```
  63   │ [options.packages.find]
  64   │ where = .
  65   │ exclude =
  66   │     tests

 ```
