### ISSUE TITLE
Add documentation on how to upgrade libraries to latest template version using cruft

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/cookiecutter-brightwaylib#16]
Using e.g. https://pypi.org/project/cookiecutter-project-upgrader/

**Comment by tngTUDOR** [comment]
Another option would be to use [cruft](https://cruft.github.io/cruft/) as the rendering engine, and profit from it's u[pdate feature](https://cruft.github.io/cruft/#updating-a-project).

[pros]
+ fully compatible with cookiecutter templates
+ can be used with "already generated by cookiecutter" projects
+ uses git commit id as a means to identify which version of the cookiecutter template was originally used

[cons]
- another tool

**Comment by cmutel** [comment]
+1 to cruft, it is actually being maintained.
