### ISSUE TITLE
Bring `docs` folders/files in Line with the Brightway Documentation

### ISSUE THREAD

**Issue by michaelweinold** [brightway-lca/cookiecutter-brightwaylib#20]

**Comment by tngTUDOR** [comment]
@michaelweinold  can you be a bit more specific on this ?

I suppose we need to add "docs/contents" for example, instead of having everything on "docs" and so on.

**Comment by michaelweinold** [comment]
...as far as I can see, this was already resolved with: https://github.com/brightway-lca/cookiecutter-brightwaylib/commit/963557920a6f7fab95f46601e05a8ffc08deec37

I think we can close this issue.
