### ISSUE TITLE
Move `.readthedocs.yml` to `.readthedocs.yaml`

### ISSUE THREAD

**Issue by cmutel** [brightway-lca/cookiecutter-brightwaylib#52]
Setting up new repos with RTFD requires *exactly* `.readthedocs.yaml`:

<img width="335" alt="Screenshot 2024-12-19 at 13 53 29" src="https://github.com/user-attachments/assets/baa62cff-a33c-46e3-89ed-5eeff1d0a08c" />

@michaelweinold Any objections or things that would break with the docs pipeline?

**Comment by michaelweinold** [comment]
Checked just now - did not find anything that would break.

**Comment by cmutel** [comment]
Fixed in #53
